Repository ssydney77/ProjetGit-TemplatePortfolio, pull requests merged in 2023-03, with the labels that each got.

#15 fix and update template for pull request
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
Labels: bug, enhancement

#21 update contributing.md
  CONTRIBUTING.md
Labels: documentation

#30 Ajout de la Version 4 du template
  public/html/index-4.html
Labels: enhancement

#27 Update readme
  README.md
Labels: documentation

#28 Add new template
  public/html/index-3.html
Labels: enhancement

#32 ajout d'info dans le readme, voir la review afin de réellement voir les changements
  README.md
Labels: enhancement

#31 Changement couleur nav bar, blog page & contact page au niveau du css
  public/assets/css/topbar.virtual.css
Labels: enhancement
